# -*- coding: utf-8 -*-
"""Numpy0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SCH93cxY7BpOf7RVK-Hgh4mclePT-B5
"""

import numpy as np
print(np.__version__)

import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

import numpy as np
arr=np.array([[1,2,3],[6,7,8]])
print(arr)

import numpy as np
arr=np.array([[[1,2,3],[6,7,8],[4,5,8]]])
print(arr)

import numpy as np
arr=np.zeros((10,3))
print(arr)

import numpy as np
arr=np.ones((5,7))
print(arr)

import numpy as np
arr=np.full((5,7),3)
print(arr)

import numpy as np
arr=np.empty((5,5))
print(arr)

import numpy as np
arr=np.eye((5))
print(arr)

import numpy as np
arr=np.arange(1,100)
print(arr)

import numpy as np
Even=np.arange(2,200,2)
print(Even)

import numpy as np
Odd=np.arange(1,200,2)
print(Odd)

import numpy as np
arr=np.linspace(1,10,5)
print(arr)

import numpy as np
arr=np.random.rand(10)
print(arr)

import numpy as np
arr=np.random.randn(10)
print(arr)

import numpy as np
arr=np.random.randint(10)
print(arr)

import numpy as np
colour=["Black","white","red","orange","pink","Green"]
print(np.random.choice(colour,3))

#copy
import numpy as np
arr=np.array([1,2,3,4,5])
new=arr.copy()
new[0]=42
print(arr)
print(new)

#view()
import numpy as np
arr=np.array([1,2,3,4,5])
new=arr.view()
new[1]=42
print(arr)
print(new)

import numpy as np
arr=np.array([1,2,3,4,5])

arr+=10
print("Updated array value is",arr)

import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.add(A,B)
print(C)

import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.multiply(A,B)
print(C)

import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.subtract(A,B)
print(C)

import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.divide(A,B)
print(C)

import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
C=np.dot(A,B)
print(C)

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(sum(arr))

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(min(arr))

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(max(arr))

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.std(arr))

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sqrt(arr))

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.mean(arr))

import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.sort(arr))

import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34,1,1,1,1,2,3,4,5,6,7,8])
print(np.unique(arr))

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.size)

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.itemsize)

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.ndim)

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.dtype)

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1])

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[:,1])

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,7,8,9,0,12,45,67])
print("original array is",arr)
new=arr.reshape(4,4)
print("Reshaped array is",new)

